version: "3.7"

services:
  wordpress:
    # If you want to use the default image
    # image: wordpress:latest # https://hub.docker.com/_/wordpress/
    # If you want to build a wordpress image with default self signed certs for Apache
    # See Dockerfile
    container_name: wordpress
    image: wordpress-5-php7.4-apache-mod # updates minor WordPress versions, stays on PHP7.4 for compatibility
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROXY_IP: ${PROXY_IP}
        BASE_URL: ${BASE_URL}
    ports:
      - ${IP}:8500:80 # change ip if required
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project - if it exists, and once it exists.
      - ./cioos-siooc-wordpress-theme:/var/www/html/wp-content/themes/cioos-siooc-wordpress-theme # Theme development from this folder. - should overwrite above?
      # Below are production CIOOS Atlantic settings
      #- ${WP_CONTENT}:/var/www/html/wp-content
      #- ${WP_LOGS}:/var/log
      #- ${WEB_ACCESS_FOLDER}:/var/www/html/docs
      #- ${METADATA_FOLDER}:/var/www/html/metadata
      #- ${RAW_FOLDER}:/var/www/html/raw
      #- ${PROFILE_FOLDER}:/var/www/html/profile
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_NAME: ${DOCKER_DB_NAME}
      WORDPRESS_DB_USER: ${DOCKER_DB_USER}
      WORDPRESS_DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','${BASE_URL}');
        define('WP_SITEURL','${BASE_URL}');
        define('FS_METHOD', 'direct');
        @ini_set( 'upload_max_filesize' , '1024M' );
        @ini_set( 'post_max_size', '1024M');
        @ini_set( 'memory_limit', '2048M' );
        @ini_set( 'max_execution_time', '300' );
        @ini_set( 'max_input_time', '300' );
    depends_on:
      - wp_db
    links:
      - wp_db

  wpcli:
     container_name: wpcli
     image: wordpress:cli
     volumes:
       - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
       - ./wp-app:/var/www/html
     depends_on:
       - wp_db
       - wordpress


  wp_db:
    container_name: wp_db
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - wordpress_db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}

volumes:
  db_data:
  wordpress_db_data: {}

