version: '3.4'

services:
  wp:
    # If you want to use the default image
    # image: wordpress:latest # https://hub.docker.com/_/wordpress/
    # If you want to build a wordpress image with default self signed certs for Apache
    # See Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${IP}:80:80 # change ip if required
      - ${IP}:443:443 
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DOCKER_DB_NAME}
      WORDPRESS_DB_USER: ${DOCKER_DB_USER}
      WORDPRESS_DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      # WORDPRESS_CONFIG_EXTRA: 
      #   define('WP_DEBUG', true );
      #   define('WP_HOME','http://cioos.local');
      #   define('WP_SITEURL','http://cioos.local');
    depends_on:
      - db
    links:
      - db

  # wpcli:
  #   image: wordpress:cli
  #   volumes:
  #     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
  #     - ./wp-app:/var/www/html
  #   depends_on:
  #     - db
  #     - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - ${IP}:8080:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}

volumes:
  db_data:
