version: "3.7"

services:
  wordpress:
    build: ./wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: &dbuser ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: &dbpassword ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: &dbname ${WORDPRESS_DB_NAME}
    volumes:
      - wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: *dbname
      MYSQL_USER: *dbuser
      MYSQL_PASSWORD: *dbpassword
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  wp-content:
  db-data:
